/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author juani
 */
import Clases.Resistencia2;
import java.awt.Color;
import java.awt.Toolkit;

public class Resistencia_5Bandas extends javax.swing.JFrame {

    Resistencia2 res = new Resistencia2();
   
    public Resistencia_5Bandas() {
        initComponents();
        this.setLocationRelativeTo(null);
        resultado.setEditable(false);
        this.getContentPane().setBackground((new Color(239, 239, 239))); 
        this.setTitle("Resistencia de 5 Bandas");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/iconores.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        R4Bandas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Banda1Color = new javax.swing.JButton();
        MultColor = new javax.swing.JButton();
        TolColor = new javax.swing.JButton();
        Banda2Color = new javax.swing.JButton();
        ListaColores1 = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        ListaColores2 = new javax.swing.JComboBox<>();
        resultado = new javax.swing.JTextField();
        ListaMultiplicador = new javax.swing.JComboBox<>();
        ListaTolerancia = new javax.swing.JComboBox<>();
        ListaColores3 = new javax.swing.JComboBox<>();
        Banda3Color = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtColorB1 = new javax.swing.JLabel();
        txtColorB2 = new javax.swing.JLabel();
        txtColorB3 = new javax.swing.JLabel();
        txtColorM = new javax.swing.JLabel();
        txtColorT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        R4Bandas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4-icon-ress.png"))); // NOI18N
        R4Bandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R4BandasActionPerformed(evt);
            }
        });
        getContentPane().add(R4Bandas, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, 80));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        Banda1Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Banda1ColorActionPerformed(evt);
            }
        });
        getContentPane().add(Banda1Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 68, 105, 25));

        MultColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultColorActionPerformed(evt);
            }
        });
        getContentPane().add(MultColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 196, 90, 25));
        getContentPane().add(TolColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 270, 106, 24));

        Banda2Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Banda2ColorActionPerformed(evt);
            }
        });
        getContentPane().add(Banda2Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 119, 85, 27));

        ListaColores1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        ListaColores1.setForeground(new java.awt.Color(255, 255, 255));
        ListaColores1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Gris", "Blanco" }));
        ListaColores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaColores1ActionPerformed(evt);
            }
        });
        getContentPane().add(ListaColores1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 30));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        ListaColores2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        ListaColores2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Gris", "Blanco" }));
        ListaColores2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaColores2ActionPerformed(evt);
            }
        });
        getContentPane().add(ListaColores2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 30));

        resultado.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 189, 40));

        ListaMultiplicador.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        ListaMultiplicador.setForeground(new java.awt.Color(255, 255, 255));
        ListaMultiplicador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Gris", "Blanco", "Oro", "Plateado" }));
        ListaMultiplicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaMultiplicadorActionPerformed(evt);
            }
        });
        getContentPane().add(ListaMultiplicador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, 30));

        ListaTolerancia.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        ListaTolerancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marrón", "Rojo", "Verde", "Azul", "Violeta", "Gris", "Oro", "Plata", "Sin Banda" }));
        ListaTolerancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaToleranciaActionPerformed(evt);
            }
        });
        getContentPane().add(ListaTolerancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 100, 30));

        ListaColores3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        ListaColores3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Gris", "Blanco" }));
        ListaColores3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaColores3ActionPerformed(evt);
            }
        });
        getContentPane().add(ListaColores3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 30));

        Banda3Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Banda3ColorActionPerformed(evt);
            }
        });
        getContentPane().add(Banda3Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 157, 88, 26));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5-resis-taba.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 110, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono-inform.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, 70));

        jPanel1.setBackground(new java.awt.Color(255, 213, 105));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Color 1.ª Banda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 120, 40));

        jPanel2.setBackground(new java.awt.Color(154, 173, 255));

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Color 2.ª Banda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 120, 40));

        jPanel3.setBackground(new java.awt.Color(244, 1, 172));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Color 3.ª Banda");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 120, 40));

        jPanel4.setBackground(new java.awt.Color(244, 142, 227));

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Multiplicador");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 110, 40));

        jPanel5.setBackground(new java.awt.Color(40, 200, 120));

        jLabel10.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tolerancia");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevamente-2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 110, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevamente-2.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 110, 80));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevamente-2.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 110, 80));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevamente-2.png"))); // NOI18N
        jLabel12.setText("jLabel3");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 110, 80));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevamente-2.png"))); // NOI18N
        jLabel13.setText("jLabel3");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 110, 80));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevamente-2.png"))); // NOI18N
        jLabel14.setText("jLabel3");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 110, 80));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevamente-2.png"))); // NOI18N
        jLabel16.setText("jLabel3");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 110, 60));

        txtColorB1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtColorB1.setText("()");
        getContentPane().add(txtColorB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        txtColorB2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtColorB2.setText("()");
        getContentPane().add(txtColorB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        txtColorB3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtColorB3.setText("()");
        getContentPane().add(txtColorB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        txtColorM.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtColorM.setText("()");
        getContentPane().add(txtColorM, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        txtColorT.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtColorT.setText("()");
        getContentPane().add(txtColorT, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void R4BandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R4BandasActionPerformed
       //Abre la ventanda de 4 Bandas 
       Resistencia_4Bandas  abrir = new Resistencia_4Bandas();
       abrir.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_R4BandasActionPerformed

    private void MultColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MultColorActionPerformed

    private void ListaColores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaColores1ActionPerformed

        //Hace el cambio de color de la barra designada
        int Banda1 = ListaColores1.getSelectedIndex();
        switch(Banda1){
            case 0 -> Banda1Color.setBackground(Color.BLACK);
            case 1 -> Banda1Color.setBackground(new Color(128, 64, 0)); //Marrón
            case 2 -> Banda1Color.setBackground(Color.red);
            case 3 -> Banda1Color.setBackground(new Color(255,94,5)); //Naranja
            case 4 -> Banda1Color.setBackground(Color.YELLOW);
            case 5 -> Banda1Color.setBackground(new Color(0, 128, 0));//Verde
            case 6 -> Banda1Color.setBackground(Color.BLUE);
            case 7 -> Banda1Color.setBackground(new Color(128, 0, 255));//Violeta
            case 8 -> Banda1Color.setBackground(Color.GRAY);
            case 9 -> Banda1Color.setBackground(Color.WHITE);
            default -> Banda1Color.setBackground(new Color(253, 221, 202));//Piel
        }
        this.txtColorB1.setText("("+Integer.toString(Banda1)+")");

    }//GEN-LAST:event_ListaColores1ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        
        //coloca los valores a los atributos
        res.setBanda1(ListaColores1.getSelectedIndex());
        res.setBanda2(ListaColores2.getSelectedIndex());
        res.setBanda3(ListaColores3.getSelectedIndex());
        res.setTolerancia(Integer.toString(ListaTolerancia.getSelectedIndex()));
        res.setMultiplicador(Integer.toString(ListaMultiplicador.getSelectedIndex()));

        //resultado lo imprime en la caja final
        this.resultado.setText(res.multiplicacion());

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void ListaColores2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaColores2ActionPerformed

        //Hace el cambio de color de la barra designada
        int Banda2 = ListaColores2.getSelectedIndex();
        switch(Banda2){
            case 0 -> Banda2Color.setBackground(Color.BLACK);
            case 1 -> Banda2Color.setBackground(new Color(128, 64, 0)); //Marrón
            case 2 -> Banda2Color.setBackground(Color.red);
            case 3 -> Banda2Color.setBackground(new Color(255,94,5));//Naranja
            case 4 -> Banda2Color.setBackground(Color.YELLOW);
            case 5 -> Banda2Color.setBackground(new Color(0, 128, 0)); //Verde
            case 6 -> Banda2Color.setBackground(Color.BLUE);
            case 7 -> Banda2Color.setBackground(new Color(128, 0, 255));//Violeta
            case 8 -> Banda2Color.setBackground(Color.GRAY);
            case 9 -> Banda2Color.setBackground(Color.WHITE);
            default -> Banda2Color.setBackground(new Color(253, 221, 202));//Piel
        }
        this.txtColorB2.setText("("+Integer.toString(Banda2)+")");

    }//GEN-LAST:event_ListaColores2ActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoActionPerformed

    private void ListaMultiplicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaMultiplicadorActionPerformed

        //Hace el cambio de color de la barra designada
        int MultC = ListaMultiplicador.getSelectedIndex();
        switch(MultC){
            case 0 -> MultColor.setBackground(Color.BLACK);
            case 1 -> MultColor.setBackground(new Color(128, 64, 0)); //Marrón
            case 2 -> MultColor.setBackground(Color.red);
            case 3 -> MultColor.setBackground(new Color(255,94,5));//Naranja
            case 4 -> MultColor.setBackground(Color.YELLOW);
            case 5 -> MultColor.setBackground(new Color(0, 128, 0));//Verde
            case 6 -> MultColor.setBackground(Color.BLUE);
            case 7 -> MultColor.setBackground(new Color(128, 0, 255));//Violeta
            case 8 -> MultColor.setBackground(Color.GRAY);
            case 9 -> MultColor.setBackground(Color.WHITE);
            case 10 -> MultColor.setBackground(new Color(200,150,41)); //Dorado
            case 11 -> MultColor.setBackground(new Color(170,169,173)); //Plateado
            default -> MultColor.setBackground(new Color(253, 221, 202));//Piel
        }
                String mostrarMult = Integer.toString(ListaMultiplicador.getSelectedIndex());
                String[] Mult = {"(x1 Ω)","(x10 Ω)","(x100 Ω)","(x1000 Ω)","(x10 kΩ)",
                                "(x100 kΩ)","(x1 MΩ)","(x10 MΩ)","(x100 MΩ)","(x1 GΩ)",
                                "(x0.1 Ω)","(x0.01 Ω)"};
                switch(mostrarMult){
                    case "0" -> this.txtColorM.setText(Mult[0]);
                    case "1"  -> this.txtColorM.setText(Mult[1]); 
                    case "2"  -> this.txtColorM.setText(Mult[2]);
                    case "3"  -> this.txtColorM.setText(Mult[3]);
                    case "4"  -> this.txtColorM.setText(Mult[4]);
                    case "5"  -> this.txtColorM.setText(Mult[5]);
                    case "6"  -> this.txtColorM.setText(Mult[6]);
                    case "7" -> this.txtColorM.setText(Mult[7]);
                    case "8" -> this.txtColorM.setText(Mult[8]);
                    case "9" -> this.txtColorM.setText(Mult[9]);
                    case "10" -> this.txtColorM.setText(Mult[10]);
                    case "11" -> this.txtColorM.setText(Mult[11]);
                    default -> this.txtColorM.setText("()");     
                } 
    }//GEN-LAST:event_ListaMultiplicadorActionPerformed

    private void ListaToleranciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaToleranciaActionPerformed

        //Hace el cambio de color de la barra designada
        int TolC = ListaTolerancia.getSelectedIndex();
        switch(TolC){
            case 0 -> TolColor.setBackground(new Color(128, 64, 0)); //Marrón
            case 1 -> TolColor.setBackground(Color.RED);
            case 2 -> TolColor.setBackground(new Color(0, 128, 0));//Verde
            case 3 -> TolColor.setBackground(Color.BLUE);
            case 4 -> TolColor.setBackground(new Color(128, 0, 255)); //Violeta
            case 5 -> TolColor.setBackground(Color.GRAY);
            case 6 -> TolColor.setBackground(new Color(200,150,41)); //Dorado
            case 7 -> TolColor.setBackground(new Color(170,169,173));//Plateado
            case 8 -> TolColor.setBackground(new Color(253, 221, 202));//Piel
            default -> TolColor.setBackground(new Color(253, 221, 202));
        }
                String mostrarTol = Integer.toString(ListaTolerancia.getSelectedIndex());
                String[] Tol = {"(±1%)","(±2%)","(±0.5%)","(±0.25%)","(±0.10%)","(±0.05%)","(±5%)","(±10%)","(±20%)"};
                switch(mostrarTol){
                    case "0" -> this.txtColorT.setText(Tol[0]);
                    case "1"  -> this.txtColorT.setText(Tol[1]); 
                    case "2"  -> this.txtColorT.setText(Tol[2]);
                    case "3"  -> this.txtColorT.setText(Tol[3]);
                    case "4"  -> this.txtColorT.setText(Tol[4]);
                    case "5"  -> this.txtColorT.setText(Tol[5]);
                    case "6"  -> this.txtColorT.setText(Tol[6]);
                    case "7" -> this.txtColorT.setText(Tol[7]);
                    case "8" -> this.txtColorT.setText(Tol[8]);
                    default -> this.txtColorT.setText("()");     
                }
    }//GEN-LAST:event_ListaToleranciaActionPerformed

    private void Banda2ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Banda2ColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Banda2ColorActionPerformed

    private void Banda3ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Banda3ColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Banda3ColorActionPerformed

    private void ListaColores3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaColores3ActionPerformed
          //Hace el cambio de color de la barra designada
          int Banda3 = ListaColores3.getSelectedIndex();
        switch(Banda3){
            case 0 -> Banda3Color.setBackground(Color.BLACK);
            case 1 -> Banda3Color.setBackground(new Color(128, 64, 0)); //Marrón
            case 2 -> Banda3Color.setBackground(Color.red);
            case 3 -> Banda3Color.setBackground(new Color(255,94,5)); //Naranja
            case 4 -> Banda3Color.setBackground(Color.YELLOW);
            case 5 -> Banda3Color.setBackground(new Color(0, 128, 0));//Verde
            case 6 -> Banda3Color.setBackground(Color.BLUE);
            case 7 -> Banda3Color.setBackground(new Color(128, 0, 255));//Violeta
            case 8 -> Banda3Color.setBackground(Color.GRAY);
            case 9 -> Banda3Color.setBackground(Color.WHITE);
            default -> Banda3Color.setBackground(new Color(253, 221, 202));//Piel
        }
        this.txtColorB3.setText("("+Integer.toString(Banda3)+")");

    }//GEN-LAST:event_ListaColores3ActionPerformed

    private void Banda1ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Banda1ColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Banda1ColorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Guia_5Bandas  abrir = new Guia_5Bandas();
       abrir.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resistencia_5Bandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resistencia_5Bandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resistencia_5Bandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resistencia_5Bandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resistencia_5Bandas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Banda1Color;
    private javax.swing.JButton Banda2Color;
    private javax.swing.JButton Banda3Color;
    private javax.swing.JComboBox<String> ListaColores1;
    private javax.swing.JComboBox<String> ListaColores2;
    private javax.swing.JComboBox<String> ListaColores3;
    private javax.swing.JComboBox<String> ListaMultiplicador;
    private javax.swing.JComboBox<String> ListaTolerancia;
    private javax.swing.JButton MultColor;
    private javax.swing.JButton R4Bandas;
    private javax.swing.JButton TolColor;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField resultado;
    private javax.swing.JLabel txtColorB1;
    private javax.swing.JLabel txtColorB2;
    private javax.swing.JLabel txtColorB3;
    private javax.swing.JLabel txtColorM;
    private javax.swing.JLabel txtColorT;
    // End of variables declaration//GEN-END:variables
}
