package Presentacion;

/**
 *
 * @author juani
 */
import Clases.Resistencia;
import java.awt.Color;
import java.awt.Toolkit;
public class Resistencia_4Bandas extends javax.swing.JFrame {

    Resistencia res = new Resistencia();
   
    
    public Resistencia_4Bandas() {
        initComponents();
        this.setLocationRelativeTo(null); //Centra la ventana
        resultado.setEditable(false); //no se puede editar la caja de resultado
        this.getContentPane().setBackground((new Color(239, 239, 239))); 
        this.setTitle("Resistencia de 4 Bandas");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/iconores.png"))); //icono de la app

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        ListaColores1 = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        ListaColores2 = new javax.swing.JComboBox<>();
        resultado = new javax.swing.JTextField();
        ListaMultiplicador = new javax.swing.JComboBox<>();
        ListaTolerancia = new javax.swing.JComboBox<>();
        Banda1Color = new javax.swing.JButton();
        MultColor = new javax.swing.JButton();
        TolColor = new javax.swing.JButton();
        Banda2Color = new javax.swing.JButton();
        R5Bandas = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtColorB1 = new javax.swing.JLabel();
        txtColorB2 = new javax.swing.JLabel();
        txtColorM = new javax.swing.JLabel();
        txtColorT = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListaColores1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        ListaColores1.setForeground(new java.awt.Color(255, 255, 255));
        ListaColores1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Gris", "Blanco" }));
        ListaColores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaColores1ActionPerformed(evt);
            }
        });
        getContentPane().add(ListaColores1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 30));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        ListaColores2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        ListaColores2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Gris", "Blanco" }));
        ListaColores2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaColores2ActionPerformed(evt);
            }
        });
        getContentPane().add(ListaColores2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 30));

        resultado.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 189, 39));

        ListaMultiplicador.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        ListaMultiplicador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Gris", "Blanco", "Oro", "Plateado" }));
        ListaMultiplicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaMultiplicadorActionPerformed(evt);
            }
        });
        getContentPane().add(ListaMultiplicador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 30));

        ListaTolerancia.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        ListaTolerancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marrón", "Rojo", "Verde", "Azul", "Violeta", "Gris", "Oro", "Plata", "Sin Banda" }));
        ListaTolerancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaToleranciaActionPerformed(evt);
            }
        });
        getContentPane().add(ListaTolerancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 120, 30));
        getContentPane().add(Banda1Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 58, 110, 24));

        MultColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultColorActionPerformed(evt);
            }
        });
        getContentPane().add(MultColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 170, 89, 34));
        getContentPane().add(TolColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 254, 106, 25));

        Banda2Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Banda2ColorActionPerformed(evt);
            }
        });
        getContentPane().add(Banda2Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 112, 90, 36));

        R5Bandas.setBackground(new java.awt.Color(239, 239, 239));
        R5Bandas.setForeground(new java.awt.Color(239, 239, 239));
        R5Bandas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5 resis icon.png"))); // NOI18N
        R5Bandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R5BandasActionPerformed(evt);
            }
        });
        getContentPane().add(R5Bandas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 70, 70));

        jButton2.setForeground(new java.awt.Color(89, 124, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono-inform.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 70, 70));

        filler1.setAutoscrolls(true);
        filler1.setBackground(new java.awt.Color(255, 102, 102));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 56, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/recortada.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, -10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 213, 105));
        jPanel2.setForeground(new java.awt.Color(255, 213, 105));

        jPanel3.setBackground(new java.awt.Color(255, 213, 105));
        jPanel3.setForeground(new java.awt.Color(255, 213, 105));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Color 1.ª Banda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 130, 40));

        jPanel4.setBackground(new java.awt.Color(154, 173, 255));
        jPanel4.setForeground(new java.awt.Color(154, 173, 255));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Color 2.ª Banda");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 130, 40));

        jPanel5.setBackground(new java.awt.Color(244, 142, 227));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Multiplicador");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 130, 40));

        jPanel6.setBackground(new java.awt.Color(40, 200, 120));

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tolerancia");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 130, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevamente.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 130, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevamente-2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 170, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevamente-2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 140, 150, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevamente-2.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 150, 70));

        txtColorB1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtColorB1.setText("()");
        getContentPane().add(txtColorB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        txtColorB2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtColorB2.setText("()");
        getContentPane().add(txtColorB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        txtColorM.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtColorM.setText("()");
        getContentPane().add(txtColorM, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        txtColorT.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtColorT.setText("()");
        getContentPane().add(txtColorT, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
       
        
        //coloca los valores a los atributos
        res.setBanda1(ListaColores1.getSelectedIndex());
        res.setBanda2(ListaColores2.getSelectedIndex());
        res.setTolerancia(Integer.toString(ListaTolerancia.getSelectedIndex()));
        res.setMultiplicador(Integer.toString(ListaMultiplicador.getSelectedIndex()));
         
        //resultado lo imprime en la caja final
        this.resultado.setText(res.multiplicacion());
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoActionPerformed

    private void ListaColores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaColores1ActionPerformed
        
        //Hace el cambio de color de la barra designada
        int Banda1 = ListaColores1.getSelectedIndex();
                switch(Banda1){
                    case 0 -> Banda1Color.setBackground(Color.BLACK);
                    case 1 -> Banda1Color.setBackground(new Color(128, 64, 0)); //Marrón
                    case 2 -> Banda1Color.setBackground(Color.red);
                    case 3 -> Banda1Color.setBackground(new Color(255,94,5)); //Naranja
                    case 4 -> Banda1Color.setBackground(Color.YELLOW);
                    case 5 -> Banda1Color.setBackground(new Color(0, 128, 0));//Verde
                    case 6 -> Banda1Color.setBackground(Color.BLUE);
                    case 7 -> Banda1Color.setBackground(new Color(128, 0, 255));//Violeta
                    case 8 -> Banda1Color.setBackground(Color.GRAY);
                    case 9 -> Banda1Color.setBackground(Color.WHITE);
                    default -> Banda1Color.setBackground(new Color(253, 221, 202));//Piel       
                }
                this.txtColorB1.setText("("+Integer.toString(Banda1)+")");
    }//GEN-LAST:event_ListaColores1ActionPerformed

    private void MultColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MultColorActionPerformed

    private void ListaColores2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaColores2ActionPerformed
                
        //Hace el cambio de color de la barra designada
                int Banda2 = ListaColores2.getSelectedIndex();
                switch(Banda2){
                    case 0 -> Banda2Color.setBackground(Color.BLACK);
                    case 1 -> Banda2Color.setBackground(new Color(128, 64, 0)); //Marrón
                    case 2 -> Banda2Color.setBackground(Color.red);
                    case 3 -> Banda2Color.setBackground(new Color(255,94,5));//Naranja
                    case 4 -> Banda2Color.setBackground(Color.YELLOW);
                    case 5 -> Banda2Color.setBackground(new Color(0, 128, 0)); //Verde
                    case 6 -> Banda2Color.setBackground(Color.BLUE);
                    case 7 -> Banda2Color.setBackground(new Color(128, 0, 255));//Violeta
                    case 8 -> Banda2Color.setBackground(Color.GRAY);
                    case 9 -> Banda2Color.setBackground(Color.WHITE);
                    default -> Banda2Color.setBackground(new Color(253, 221, 202));//Piel       
                }
                this.txtColorB2.setText("("+Integer.toString(Banda2)+")");
    }//GEN-LAST:event_ListaColores2ActionPerformed

    private void ListaMultiplicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaMultiplicadorActionPerformed
                
        //Hace el cambio de color de la barra designada
        int MultC = ListaMultiplicador.getSelectedIndex();
                switch(MultC){
                    case 0 -> MultColor.setBackground(Color.BLACK);
                    case 1 -> MultColor.setBackground(new Color(128, 64, 0)); //Marrón
                    case 2 -> MultColor.setBackground(Color.red);
                    case 3 -> MultColor.setBackground(new Color(255,94,5));//Naranja
                    case 4 -> MultColor.setBackground(Color.YELLOW);
                    case 5 -> MultColor.setBackground(new Color(0, 128, 0));//Verde
                    case 6 -> MultColor.setBackground(Color.BLUE);
                    case 7 -> MultColor.setBackground(new Color(128, 0, 255));//Violeta
                    case 8 -> MultColor.setBackground(Color.GRAY);
                    case 9 -> MultColor.setBackground(Color.WHITE);
                    case 10 -> MultColor.setBackground(new Color(200,150,41)); //Dorado
                    case 11 -> MultColor.setBackground(new Color(170,169,173)); //Plateado
                    default -> MultColor.setBackground(new Color(253, 221, 202));//Piel       
                }
                //muestra en los parentesis el valor del multiplicador
                String mostrarMult = Integer.toString(ListaMultiplicador.getSelectedIndex());
                String[] Mult = {"(x1 Ω)","(x10 Ω)","(x100 Ω)","(x1000 Ω)","(x10 kΩ)",
                                "(x100 kΩ)","(x1 MΩ)","(x10 MΩ)","(x100 MΩ)","(x1 GΩ)",
                                "(x0.1 Ω)","(x0.01 Ω)"};
                switch(mostrarMult){
                    case "0" -> this.txtColorM.setText(Mult[0]);
                    case "1"  -> this.txtColorM.setText(Mult[1]); 
                    case "2"  -> this.txtColorM.setText(Mult[2]);
                    case "3"  -> this.txtColorM.setText(Mult[3]);
                    case "4"  -> this.txtColorM.setText(Mult[4]);
                    case "5"  -> this.txtColorM.setText(Mult[5]);
                    case "6"  -> this.txtColorM.setText(Mult[6]);
                    case "7" -> this.txtColorM.setText(Mult[7]);
                    case "8" -> this.txtColorM.setText(Mult[8]);
                    case "9" -> this.txtColorM.setText(Mult[9]);
                    case "10" -> this.txtColorM.setText(Mult[10]);
                    case "11" -> this.txtColorM.setText(Mult[11]);
                    default -> this.txtColorM.setText("()");     
                }                
    }//GEN-LAST:event_ListaMultiplicadorActionPerformed

    private void ListaToleranciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaToleranciaActionPerformed
               
        //Hace el cambio de color de la barra designada
        int TolC = ListaTolerancia.getSelectedIndex();
                switch(TolC){
                    case 0 -> TolColor.setBackground(new Color(128, 64, 0)); //Marrón
                    case 1 -> TolColor.setBackground(Color.RED); 
                    case 2 -> TolColor.setBackground(new Color(0, 128, 0));//Verde
                    case 3 -> TolColor.setBackground(Color.BLUE);
                    case 4 -> TolColor.setBackground(new Color(128, 0, 255)); //Violeta
                    case 5 -> TolColor.setBackground(Color.GRAY); 
                    case 6 -> TolColor.setBackground(new Color(200,150,41)); //Dorado
                    case 7 -> TolColor.setBackground(new Color(170,169,173));//Plateado
                    case 8 -> TolColor.setBackground(new Color(253, 221, 202));//Piel 
                    default -> TolColor.setBackground(new Color(253, 221, 202));      
                }
                //mostrar en el parentesis el valor de la tolerancia    
                String mostrarTol = Integer.toString(ListaTolerancia.getSelectedIndex());
                String[] Tol = {"(±1%)","(±2%)","(±0.5%)","(±0.25%)","(±0.10%)","(±0.05%)","(±5%)","(±10%)","(±20%)"};
                switch(mostrarTol){
                    case "0" -> this.txtColorT.setText(Tol[0]);
                    case "1"  -> this.txtColorT.setText(Tol[1]); 
                    case "2"  -> this.txtColorT.setText(Tol[2]);
                    case "3"  -> this.txtColorT.setText(Tol[3]);
                    case "4"  -> this.txtColorT.setText(Tol[4]);
                    case "5"  -> this.txtColorT.setText(Tol[5]);
                    case "6"  -> this.txtColorT.setText(Tol[6]);
                    case "7" -> this.txtColorT.setText(Tol[7]);
                    case "8" -> this.txtColorT.setText(Tol[8]);
                    default -> this.txtColorT.setText("()");     
                }
    }//GEN-LAST:event_ListaToleranciaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Guia_4Bandas  abrir = new Guia_4Bandas();
       abrir.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Banda2ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Banda2ColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Banda2ColorActionPerformed

    private void R5BandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R5BandasActionPerformed
        //Abre la ventanda de 5 Bandas
        Resistencia_5Bandas  abrir = new Resistencia_5Bandas();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_R5BandasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resistencia_4Bandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resistencia_4Bandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resistencia_4Bandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resistencia_4Bandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resistencia_4Bandas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Banda1Color;
    private javax.swing.JButton Banda2Color;
    private javax.swing.JComboBox<String> ListaColores1;
    private javax.swing.JComboBox<String> ListaColores2;
    private javax.swing.JComboBox<String> ListaMultiplicador;
    private javax.swing.JComboBox<String> ListaTolerancia;
    private javax.swing.JButton MultColor;
    private javax.swing.JButton R5Bandas;
    private javax.swing.JButton TolColor;
    private javax.swing.JButton btnCalcular;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton2;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField resultado;
    private javax.swing.JLabel txtColorB1;
    private javax.swing.JLabel txtColorB2;
    private javax.swing.JLabel txtColorM;
    private javax.swing.JLabel txtColorT;
    // End of variables declaration//GEN-END:variables
}
